### ISSUE TITLE
Editor Text Block

### ISSUE THREAD

**Issue by skistaddy** [ElementalCode/elemental#224] opened 2016-04-05 22:57 UTC
It is not updating to the current text.
![script](http://imagizer.imageshack.us/v2/252x198q90/921/L7AYMN.png)
Any idea on how to fix?

**Comment by towerofnix** [comment] 2016-04-05 23:11
Works for me on https://elementalcode.herokuapp.com/projects/editor as well as on http://elementalcode.github.io/elemental/ -- anything appear in the console?

**Comment by skistaddy** [comment] 2016-04-06 01:10
Hmm... It isn't updating the HTML viewer. I'll try again later. :P

**Comment by iamunknown2** [comment] 2016-04-06 13:07
Not working for me (the guy who wrote the fix) as well. Hmm...

**Comment by matthewr6** [comment] 2016-04-06 14:06
http://prntscr.com/aov0p9
Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

**Comment by towerofnix** [comment] 2016-04-06 14:06
What web browsers are you guys using? I'm on Firefox 48, and it works for me.

**Comment by matthewr6** [comment] 2016-04-06 14:06
Chrome something

**Comment by towerofnix** [comment] 2016-04-06 14:08
> Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

Probably they're using https://elementalcode.herokuapp.com/ ?

**Comment by skistaddy** [comment] 2016-04-06 15:56
Yeah, that URL that Liam said and I use chrome.

**Comment by towerofnix** [comment] 2016-04-06 16:46
You should be using http://elementalcode.github.io/. Also, both editors work for me running Chrome 51.

**Comment by matthewr6** [comment] 2016-04-06 20:58
Chrome (I assume 51) on Windows for me and OS X for liam... what OS are you using?

also 

> http://prntscr.com/aov0p9
> Not quite sure why yours has angle brackets - are you using a local copy that's outdated?

**Comment by towerofnix** [comment] 2016-04-06 21:07
> also

They're using https://elementalcode.herokuapp.com/ which hasn't been updated yet.

**Comment by skistaddy** [comment] 2016-04-06 21:19
I used your link and it didn't work. :/

**Comment by BookOwl** [comment] 2016-04-06 21:23
@bjskistad which link?

**Comment by matthewr6** [comment] 2016-04-06 21:32
@liam4 Oh ok I'll get around to updating that....
maybe....

**Comment by iamunknown2** [comment] 2016-04-11 13:19
It doesn't work on Firefox...

**Comment by skistaddy** [comment] 2016-04-30 15:57
@liam4 It updates when I click outside of the block on the workspace, but not when I'm typing.

**Comment by matthewr6** [comment] 2016-04-30 15:58
Please give your chrome version.  Is this on the github pages site?

**Comment by skistaddy** [comment] 2016-04-30 16:01
Yes it is on the GH pages.I believe this is my OS: ChromeOS 7834.70.0 The other one looks like my IP.

**Comment by skistaddy** [comment] 2016-04-30 16:01
I'm using chrome: Chrome 49.0.2623.112

**Comment by matthewr6** [comment] 2016-04-30 16:02
Works for me, exact same version of Chrome.  Are there any console errors?

**Comment by skistaddy** [comment] 2016-04-30 16:03
Lemme check...

**Comment by skistaddy** [comment] 2016-04-30 16:04
I got your guys' logo then this: `ncaught TypeError: Cannot read property 'addEventListener' of null`

**Comment by matthewr6** [comment] 2016-04-30 16:04
What line?
A screenshot of the console would be nice

**Comment by skistaddy** [comment] 2016-04-30 16:05
K.

**Comment by skistaddy** [comment] 2016-04-30 16:08
http://imgur.com/qtdDLD8

**Comment by matthewr6** [comment] 2016-04-30 16:34
Should be fixed - make sure to clear your cache

**Comment by skistaddy** [comment] 2016-04-30 19:04
K.

**Comment by skistaddy** [comment] 2016-04-30 19:04
Nope, wasn't fixed.

**Comment by matthewr6** [comment] 2016-04-30 20:06
Please show your console again, then - that's more helpful than just "wasn't fixed"
I'm going to leave this closed until anybody but you can replicate it, though... because it seems to be a unique occurrence based on what others have said

**Comment by skistaddy** [comment] 2016-04-30 20:08
Nothing wrong with it.

**Comment by matthewr6** [comment] 2016-04-30 20:09
What do you mean?

**Comment by skistaddy** [comment] 2016-04-30 20:09
No errors.

**Comment by matthewr6** [comment] 2016-04-30 20:11
But... it still doesn't work?  @ElementalCode/programmers guys please confirm then

**Comment by TheInitializer** [comment] 2016-04-30 21:03
By this I assume you mean updating the preview as you type? If so it works for me on both versions (Firefox Developer Edition 48.0a2 with e10s on windows 10 64-bit)

**Comment by skistaddy** [comment] 2016-04-30 21:08
Yes. Doesn't work for me though.

**Comment by matthewr6** [comment] 2016-04-30 21:54
It works for me on both versions too... Latest Chrome, and windows 10

**Comment by matthewr6** [comment] 2016-04-30 21:56
@TheInitializer if only one person has reported it and it's not reproducible by anyone else I'm going to close it for now

**Comment by skistaddy** [comment] 2016-04-30 21:56
Lucky...

**Comment by matthewr6** [comment] 2016-04-30 21:57
Did you clear your cache?

**Comment by TheInitializer** [comment] 2016-04-30 21:57
^^

**Closed as completed by matthewr6** 2016-04-30 21:56 UTC

**Comment by skistaddy** [comment] 2016-04-30 21:59
YES I DID. I CLEARED MY WHOLE CACHE AND IT DIDN'T WORKED.

**Comment by matthewr6** [comment] 2016-04-30 22:04
No need for all caps.

http://elementalcode.github.io/elemental/resources/js/blocks.js
Please do a search for `'keydown'` and see if there are any results in the file.

**Comment by towerofnix** [comment] 2016-04-30 22:08
No results for me.

**Comment by TheInitializer** [comment] 2016-04-30 23:10
nope
